# Generated by Django 3.0.2 on 2020-01-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='menstruation_start',
            field=models.DateField(verbose_name='menstruation start date'),
        ),
    ]
