# Generated by Django 3.0.2 on 2020-01-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20200112_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='record date')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Cycle')),
            ],
        ),
    ]
